# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('re', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=40)),
                ('before', models.CharField(max_length=40, null=True)),
                ('abeek', models.IntegerField(default=0)),
                ('fresh', models.IntegerField(default=1)),
            ],
        ),
    ]
