# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set([('number', 'name', 'week', 'start')]),
        ),
    ]
