# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20171031_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=40)),
                ('label', models.IntegerField()),
            ],
        ),
    ]
