# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20171115_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
