# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20171119_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='diff',
            field=models.IntegerField(default=1),
        ),
    ]
