# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_lecture_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('diff', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=10, null=True)),
                ('score', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('label', models.IntegerField(null=True)),
                ('week', models.IntegerField(default='')),
                ('start', models.FloatField(default=0.0)),
                ('finish', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='label',
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=set([('name', 'time', 'diff')]),
        ),
        migrations.AlterUniqueTogether(
            name='processed',
            unique_together=set([('name', 'start', 'diff')]),
        ),
    ]
