# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20171129_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processed',
            unique_together=set([('name', 'start', 'diff', 'week')]),
        ),
    ]
